version: "2"

services:

  pyramid:
    image: eeacms/corpus:pyramid_service
    ports:
      - "8181:6543"
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - corpus-data:/corpus
    command: sh -c "python setup.py develop && pserve production.ini"

  redis:
    image: redis

  worker:
      image: eeacms/corpus:pyramid_service
      command: sh -c "python setup.py develop && worker production.ini"
      environment:
        - REDIS_URL=redis://redis:6379/0
      volumes:
        - corpus-data:/corpus

volumes:
  corpus-data:
